{
  "formatVersion": "1.1",
  "component": {
    "group": "exthmuix.core",
    "module": "core",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
      	{
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha02.aar",
          "url": "core-1.0.0-alpha02.aar",
          "size": 46861,
          "sha512": "225976f6c014a2f105a5509f360acca73dcdaab144e8830ca45993725691a8279c4f65c930020b73effe34959f7809e294c7e9077eefab706067a3431bba6d6c",
          "sha256": "a7b3ad0625592f3d22df63216c16cb9ac20e875b024352346ad6db08bf61e16e",
          "sha1": "cc2210dd3fa32763e18d73c1807c736bb7b4f25b",
          "md5": "fe8e82430da0c991605fb5b23b00a0f6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha02.aar",
          "url": "core-1.0.0-alpha02.aar",
          "size": 46861,
          "sha512": "225976f6c014a2f105a5509f360acca73dcdaab144e8830ca45993725691a8279c4f65c930020b73effe34959f7809e294c7e9077eefab706067a3431bba6d6c",
          "sha256": "a7b3ad0625592f3d22df63216c16cb9ac20e875b024352346ad6db08bf61e16e",
          "sha1": "cc2210dd3fa32763e18d73c1807c736bb7b4f25b",
          "md5": "fe8e82430da0c991605fb5b23b00a0f6"
        }
      ]
    }
  ]
}
