{
  "formatVersion": "1.1",
  "component": {
    "group": "exthmuix.core",
    "module": "core",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
      	{
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha03.aar",
          "url": "core-1.0.0-alpha03.aar",
          "size": 46594,
          "sha512": "acc1b47a1e3ac0d97d6303ac460cd5eb1bf22869c2bfd8d5f6265065dc895eb59a5d9f321a76e1c3cb382d94923ecd4e6486f828be95226914308374d3567212",
          "sha256": "385f13625a4aab88551346d302fef82184ce8982b941d4f161e1619bcc6a9ad5",
          "sha1": "ccdbba73b68ee172646b7616ecbf5d186641f3ae",
          "md5": "172a8fddc655cb971c795d1934699d07"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha03.aar",
          "url": "core-1.0.0-alpha03.aar",
          "size": 46594,
          "sha512": "acc1b47a1e3ac0d97d6303ac460cd5eb1bf22869c2bfd8d5f6265065dc895eb59a5d9f321a76e1c3cb382d94923ecd4e6486f828be95226914308374d3567212",
          "sha256": "385f13625a4aab88551346d302fef82184ce8982b941d4f161e1619bcc6a9ad5",
          "sha1": "ccdbba73b68ee172646b7616ecbf5d186641f3ae",
          "md5": "172a8fddc655cb971c795d1934699d07"
        }
      ]
    }
  ]
}
